### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by nstepka** [scw1021/poshmark-html#1]
What is the goal of this app?  I also have a Poshmark app and am looking to team up with someone.

**Comment by scw1021** [comment]
Thanks for following this project. Poshmark is ongoing for now.
Can we have discussion on skype? 
My skype id: live:.cid.13732216fed143a6

**Comment by scw1021** [comment]
Can we have discussion on skype? 
My skype id: live:.cid.13732216fed143a6
